/**
 * attachmentAV
 * Scan files for viruses, trojans, and other kinds of malware.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AttachmentAv);
  }
}(this, function(expect, AttachmentAv) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AttachmentAv.SyncDownloadScanRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SyncDownloadScanRequest', function() {
    it('should create an instance of SyncDownloadScanRequest', function() {
      // uncomment below and update the code to test SyncDownloadScanRequest
      //var instance = new AttachmentAv.SyncDownloadScanRequest();
      //expect(instance).to.be.a(AttachmentAv.SyncDownloadScanRequest);
    });

    it('should have the property downloadUrl (base name: "download_url")', function() {
      // uncomment below and update the code to test the property downloadUrl
      //var instance = new AttachmentAv.SyncDownloadScanRequest();
      //expect(instance).to.be();
    });

    it('should have the property downloadHeaders (base name: "download_headers")', function() {
      // uncomment below and update the code to test the property downloadHeaders
      //var instance = new AttachmentAv.SyncDownloadScanRequest();
      //expect(instance).to.be();
    });

  });

}));
