/**
 * attachmentAV
 * Scan files for viruses, trojans, and other kinds of malware.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import ScanResult from './model/ScanResult';
import SyncDownloadScanRequest from './model/SyncDownloadScanRequest';
import SyncS3ScanRequest from './model/SyncS3ScanRequest';
import AttachmentAVApi from './api/AttachmentAVApi';


/**
* Scan files for viruses, trojans, and other kinds of malware..<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var WiddixAttachmentavSdkJs = require('index'); // See note below*.
* var xxxSvc = new WiddixAttachmentavSdkJs.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new WiddixAttachmentavSdkJs.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new WiddixAttachmentavSdkJs.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new WiddixAttachmentavSdkJs.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.3.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The ScanResult model constructor.
     * @property {module:model/ScanResult}
     */
    ScanResult,

    /**
     * The SyncDownloadScanRequest model constructor.
     * @property {module:model/SyncDownloadScanRequest}
     */
    SyncDownloadScanRequest,

    /**
     * The SyncS3ScanRequest model constructor.
     * @property {module:model/SyncS3ScanRequest}
     */
    SyncS3ScanRequest,

    /**
    * The AttachmentAVApi service constructor.
    * @property {module:api/AttachmentAVApi}
    */
    AttachmentAVApi
};
