/**
 * attachmentAV
 * An SDK to integrate virus and malware scan capabilities into JavaScript applications. Scan files for viruses, trojans, and other kinds of malware with attachmentAV powered by Sophos.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AsyncDownloadScanRequest model module.
 * @module model/AsyncDownloadScanRequest
 * @version 0.1.0
 */
class AsyncDownloadScanRequest {
    /**
     * Constructs a new <code>AsyncDownloadScanRequest</code>.
     * @alias module:model/AsyncDownloadScanRequest
     * @param downloadUrl {String} 
     * @param callbackUrl {String} 
     */
    constructor(downloadUrl, callbackUrl) { 
        
        AsyncDownloadScanRequest.initialize(this, downloadUrl, callbackUrl);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, downloadUrl, callbackUrl) { 
        obj['download_url'] = downloadUrl;
        obj['callback_url'] = callbackUrl;
    }

    /**
     * Constructs a <code>AsyncDownloadScanRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AsyncDownloadScanRequest} obj Optional instance to populate.
     * @return {module:model/AsyncDownloadScanRequest} The populated <code>AsyncDownloadScanRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AsyncDownloadScanRequest();

            if (data.hasOwnProperty('download_url')) {
                obj['download_url'] = ApiClient.convertToType(data['download_url'], 'String');
            }
            if (data.hasOwnProperty('download_headers')) {
                obj['download_headers'] = ApiClient.convertToType(data['download_headers'], {'String': 'String'});
            }
            if (data.hasOwnProperty('callback_url')) {
                obj['callback_url'] = ApiClient.convertToType(data['callback_url'], 'String');
            }
            if (data.hasOwnProperty('callback_headers')) {
                obj['callback_headers'] = ApiClient.convertToType(data['callback_headers'], {'String': 'String'});
            }
            if (data.hasOwnProperty('trace_id')) {
                obj['trace_id'] = ApiClient.convertToType(data['trace_id'], 'String');
            }
            if (data.hasOwnProperty('custom_data')) {
                obj['custom_data'] = ApiClient.convertToType(data['custom_data'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AsyncDownloadScanRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AsyncDownloadScanRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AsyncDownloadScanRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['download_url'] && !(typeof data['download_url'] === 'string' || data['download_url'] instanceof String)) {
            throw new Error("Expected the field `download_url` to be a primitive type in the JSON string but got " + data['download_url']);
        }
        // ensure the json data is a string
        if (data['callback_url'] && !(typeof data['callback_url'] === 'string' || data['callback_url'] instanceof String)) {
            throw new Error("Expected the field `callback_url` to be a primitive type in the JSON string but got " + data['callback_url']);
        }
        // ensure the json data is a string
        if (data['trace_id'] && !(typeof data['trace_id'] === 'string' || data['trace_id'] instanceof String)) {
            throw new Error("Expected the field `trace_id` to be a primitive type in the JSON string but got " + data['trace_id']);
        }
        // ensure the json data is a string
        if (data['custom_data'] && !(typeof data['custom_data'] === 'string' || data['custom_data'] instanceof String)) {
            throw new Error("Expected the field `custom_data` to be a primitive type in the JSON string but got " + data['custom_data']);
        }

        return true;
    }


}

AsyncDownloadScanRequest.RequiredProperties = ["download_url", "callback_url"];

/**
 * @member {String} download_url
 */
AsyncDownloadScanRequest.prototype['download_url'] = undefined;

/**
 * @member {Object.<String, String>} download_headers
 */
AsyncDownloadScanRequest.prototype['download_headers'] = undefined;

/**
 * @member {String} callback_url
 */
AsyncDownloadScanRequest.prototype['callback_url'] = undefined;

/**
 * @member {Object.<String, String>} callback_headers
 */
AsyncDownloadScanRequest.prototype['callback_headers'] = undefined;

/**
 * @member {String} trace_id
 */
AsyncDownloadScanRequest.prototype['trace_id'] = undefined;

/**
 * @member {String} custom_data
 */
AsyncDownloadScanRequest.prototype['custom_data'] = undefined;






export default AsyncDownloadScanRequest;

