/**
 * attachmentAV
 * Scan files for viruses, trojans, and other kinds of malware.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SyncS3ScanRequest model module.
 * @module model/SyncS3ScanRequest
 * @version 1.0.0
 */
class SyncS3ScanRequest {
    /**
     * Constructs a new <code>SyncS3ScanRequest</code>.
     * @alias module:model/SyncS3ScanRequest
     * @param bucket {String} 
     * @param key {String} 
     */
    constructor(bucket, key) { 
        
        SyncS3ScanRequest.initialize(this, bucket, key);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, bucket, key) { 
        obj['bucket'] = bucket;
        obj['key'] = key;
    }

    /**
     * Constructs a <code>SyncS3ScanRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SyncS3ScanRequest} obj Optional instance to populate.
     * @return {module:model/SyncS3ScanRequest} The populated <code>SyncS3ScanRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SyncS3ScanRequest();

            if (data.hasOwnProperty('bucket')) {
                obj['bucket'] = ApiClient.convertToType(data['bucket'], 'String');
            }
            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SyncS3ScanRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SyncS3ScanRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SyncS3ScanRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['bucket'] && !(typeof data['bucket'] === 'string' || data['bucket'] instanceof String)) {
            throw new Error("Expected the field `bucket` to be a primitive type in the JSON string but got " + data['bucket']);
        }
        // ensure the json data is a string
        if (data['key'] && !(typeof data['key'] === 'string' || data['key'] instanceof String)) {
            throw new Error("Expected the field `key` to be a primitive type in the JSON string but got " + data['key']);
        }
        // ensure the json data is a string
        if (data['version'] && !(typeof data['version'] === 'string' || data['version'] instanceof String)) {
            throw new Error("Expected the field `version` to be a primitive type in the JSON string but got " + data['version']);
        }

        return true;
    }


}

SyncS3ScanRequest.RequiredProperties = ["bucket", "key"];

/**
 * @member {String} bucket
 */
SyncS3ScanRequest.prototype['bucket'] = undefined;

/**
 * @member {String} key
 */
SyncS3ScanRequest.prototype['key'] = undefined;

/**
 * @member {String} version
 */
SyncS3ScanRequest.prototype['version'] = undefined;






export default SyncS3ScanRequest;

