/**
 * attachmentAV
 * Scan files for viruses, trojans, and other kinds of malware.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AttachmentAv);
  }
}(this, function(expect, AttachmentAv) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AttachmentAv.AttachmentAVApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AttachmentAVApi', function() {
    describe('scanSyncBinaryPost', function() {
      it('should call scanSyncBinaryPost successfully', function(done) {
        //uncomment below and update the code to test scanSyncBinaryPost
        //instance.scanSyncBinaryPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('scanSyncDownloadPost', function() {
      it('should call scanSyncDownloadPost successfully', function(done) {
        //uncomment below and update the code to test scanSyncDownloadPost
        //instance.scanSyncDownloadPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('scanSyncFormPost', function() {
      it('should call scanSyncFormPost successfully', function(done) {
        //uncomment below and update the code to test scanSyncFormPost
        //instance.scanSyncFormPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('scanSyncS3Post', function() {
      it('should call scanSyncS3Post successfully', function(done) {
        //uncomment below and update the code to test scanSyncS3Post
        //instance.scanSyncS3Post(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
